//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rupbes.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Действия.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (АП ГП «БЭС»).
        /// </summary>
        public static string APGPBes {
            get {
                return ResourceManager.GetString("APGPBes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АРМ инженера OT и ПБ.
        /// </summary>
        public static string ARM_OTPB {
            get {
                return ResourceManager.GetString("ARM_OTPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Анализ и учет заключенных договоров в строительстве.
        /// </summary>
        public static string ARMContractBuilding {
            get {
                return ResourceManager.GetString("ARMContractBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОАО «Белэлектромонтажналадка».
        /// </summary>
        public static string Belelectromontagnaladka {
            get {
                return ResourceManager.GetString("Belelectromontagnaladka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОАО «Белэнергосвязь».
        /// </summary>
        public static string Belenergosvyaz {
            get {
                return ResourceManager.GetString("Belenergosvyaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОАО «Белэнергозащита».
        /// </summary>
        public static string Belenergozaschita {
            get {
                return ResourceManager.GetString("Belenergozaschita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОАО «Белсельэлектросетьстрой».
        /// </summary>
        public static string Belselelectrosetstroi {
            get {
                return ResourceManager.GetString("Belselelectrosetstroi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Руководство.
        /// </summary>
        public static string Bosses {
            get {
                return ResourceManager.GetString("Bosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карьера.
        /// </summary>
        public static string Career {
            get {
                return ResourceManager.GetString("Career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на современная динамично развивающаяся компания. Мы выполняем все виды строительно-монтажных работ, и нам доверяют самые сложные проекты. Наша организация дорожит своей репутацией надёжного партнёра, а потому мы заинтересованы в том, чтобы у нас работали инициативные, целеустремлённые, энергичные, творческие люди, которые умеют идти к поставленной цели в команде, не боятся брать на себя ответственность, всегда готовы учиться новому. Если вы хотите стать частью нашей команды, -- приходите к нам (все вакансии вы [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string CareerFirstPart {
            get {
                return ResourceManager.GetString("CareerFirstPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на с указанием вакансии, на которую претендуете. Мы обязательно рассмотрим вашу анкету..
        /// </summary>
        public static string CareerFourthPart {
            get {
                return ResourceManager.GetString("CareerFourthPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приглашаем на работу.
        /// </summary>
        public static string CareerImgText {
            get {
                return ResourceManager.GetString("CareerImgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всю необходимую информацию и контакты Вы можете получить в разделе.
        /// </summary>
        public static string CareerSecondPart {
            get {
                return ResourceManager.GetString("CareerSecondPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Если вдруг вы не нашли интересующую вас вакансию, вы можете отправить своё резюме на электронную почту.
        /// </summary>
        public static string CareerThirdPart {
            get {
                return ResourceManager.GetString("CareerThirdPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разрешительные документы.
        /// </summary>
        public static string Certificates {
            get {
                return ResourceManager.GetString("Certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дочерние предприятия.
        /// </summary>
        public static string ChildCompanys {
            get {
                return ResourceManager.GetString("ChildCompanys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ru.
        /// </summary>
        public static string ChoosedLang {
            get {
                return ResourceManager.GetString("ChoosedLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите категорию товара.
        /// </summary>
        public static string ChooseGroupProduct {
            get {
                return ResourceManager.GetString("ChooseGroupProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код ТН ВЭД.
        /// </summary>
        public static string CodeTNVED {
            get {
                return ResourceManager.GetString("CodeTNVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Республиканское унитарное предприятие.
        /// </summary>
        public static string CompanyAbbr {
            get {
                return ResourceManager.GetString("CompanyAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Структура холдинга - «Белэнергострой холдинг».
        /// </summary>
        public static string CompanyBranches {
            get {
                return ResourceManager.GetString("CompanyBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Структура холдинга.
        /// </summary>
        public static string CompanyBranchesShort {
            get {
                return ResourceManager.GetString("CompanyBranchesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наряду с энергетическими сооружениями, построено множество объектов промышленного назначения – заводы: объемного домостроения, железобетонных изделий и конструкций, керамзитового гравия, электромеханический в городах Беларуси, высоковольтной аппаратуры в г. Великие Луки (РФ), а также мелькомбинаты, хладокомбинаты, газокомпрессорные станции и др.&lt;br&gt;
        ///Возводились и сложные по своим конструктивным решениям здания. Это аэровокзал, Дом мебели и ДРЦ Национального Банка РБ в г. Минске, ледовые дворцы, спортзалы и [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string CompanyMainText {
            get {
                return ResourceManager.GetString("CompanyMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на БЕЛЭНЕРГОСТРОЙ - УПРАВЛЯЮЩАЯ КОМПАНИЯ ХОЛДИНГА.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на День приема.
        /// </summary>
        public static string ContactsMeetDay {
            get {
                return ResourceManager.GetString("ContactsMeetDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время приема.
        /// </summary>
        public static string ContactsMeetTime {
            get {
                return ResourceManager.GetString("ContactsMeetTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ф.И.О..
        /// </summary>
        public static string ContactsName {
            get {
                return ResourceManager.GetString("ContactsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон.
        /// </summary>
        public static string ContactsPhone {
            get {
                return ResourceManager.GetString("ContactsPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Должность.
        /// </summary>
        public static string ContactsPost {
            get {
                return ResourceManager.GetString("ContactsPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Личный прием.
        /// </summary>
        public static string ContactsPrivate {
            get {
                return ResourceManager.GetString("ContactsPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа с общественностью.
        /// </summary>
        public static string ContactsPublic {
            get {
                return ResourceManager.GetString("ContactsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расширенный поиск.
        /// </summary>
        public static string DirAdvSearch {
            get {
                return ResourceManager.GetString("DirAdvSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите отдел.
        /// </summary>
        public static string DirChooseDep {
            get {
                return ResourceManager.GetString("DirChooseDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите филиал.
        /// </summary>
        public static string DirChooseFil {
            get {
                return ResourceManager.GetString("DirChooseFil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя или воспользуйтесь расширенным поиском.
        /// </summary>
        public static string DirSearchPlaceholder {
            get {
                return ResourceManager.GetString("DirSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОАО «Электроцентрмонтаж».
        /// </summary>
        public static string Electrocentrmontaj {
            get {
                return ResourceManager.GetString("Electrocentrmontaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Электронный адрес.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Электронный справочник.
        /// </summary>
        public static string EmailDirectory {
            get {
                return ResourceManager.GetString("EmailDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОАО «Энерготехпром».
        /// </summary>
        public static string Energotehprom {
            get {
                return ResourceManager.GetString("Energotehprom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Факс.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск по категориям.
        /// </summary>
        public static string FindByCategories {
            get {
                return ResourceManager.GetString("FindByCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рус.
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ГПО «Белэнерго».
        /// </summary>
        public static string LinkBelenrgo {
            get {
                return ResourceManager.GetString("LinkBelenrgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Министерство энергетики.
        /// </summary>
        public static string LinkMinenergo {
            get {
                return ResourceManager.GetString("LinkMinenergo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Национальный правовой Интернет-портал Республики Беларусь.
        /// </summary>
        public static string LinkPravoby {
            get {
                return ResourceManager.GetString("LinkPravoby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Официальный интернет-портал Президента Республики Беларусь.
        /// </summary>
        public static string LinkPresident {
            get {
                return ResourceManager.GetString("LinkPresident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работаем по мировым стандартам качества.
        /// </summary>
        public static string MainPageCertificates {
            get {
                return ResourceManager.GetString("MainPageCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5 филиалов по всей Республике.
        /// </summary>
        public static string MainPageFilials {
            get {
                return ResourceManager.GetString("MainPageFilials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сотни объектов по всей стране и за рубежом.
        /// </summary>
        public static string MainPageObjects {
            get {
                return ResourceManager.GetString("MainPageObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Широкий спектр товаров и услуг.
        /// </summary>
        public static string MainPageServices {
            get {
                return ResourceManager.GetString("MainPageServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карьера в компании.
        /// </summary>
        public static string MainPageVacancies {
            get {
                return ResourceManager.GetString("MainPageVacancies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название или код ТНВЭД.
        /// </summary>
        public static string MaterialSearchLine {
            get {
                return ResourceManager.GetString("MaterialSearchLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АРМ инженера ОГМ.
        /// </summary>
        public static string Mechanic {
            get {
                return ResourceManager.GetString("Mechanic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Антикоррупционная деятельность.
        /// </summary>
        public static string MenuAntiCorruptionNews {
            get {
                return ResourceManager.GetString("MenuAntiCorruptionNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О холдинге.
        /// </summary>
        public static string MenuCompany {
            get {
                return ResourceManager.GetString("MenuCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты.
        /// </summary>
        public static string MenuContacts {
            get {
                return ResourceManager.GetString("MenuContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Год качества.
        /// </summary>
        public static string MenuCurrentYear {
            get {
                return ResourceManager.GetString("MenuCurrentYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правовое просвещение.
        /// </summary>
        public static string MenuLegalEducation {
            get {
                return ResourceManager.GetString("MenuLegalEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Безопасность жизнедеятельности.
        /// </summary>
        public static string MenuLifeSafetyNews {
            get {
                return ResourceManager.GetString("MenuLifeSafetyNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новости.
        /// </summary>
        public static string MenuNews {
            get {
                return ResourceManager.GetString("MenuNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объекты.
        /// </summary>
        public static string MenuObj {
            get {
                return ResourceManager.GetString("MenuObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закупки.
        /// </summary>
        public static string MenuPurchases {
            get {
                return ResourceManager.GetString("MenuPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Безопасность дорожного движения.
        /// </summary>
        public static string MenuRoadSafety {
            get {
                return ResourceManager.GetString("MenuRoadSafety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Услуги.
        /// </summary>
        public static string MenuServices {
            get {
                return ResourceManager.GetString("MenuServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новости общественной жизни.
        /// </summary>
        public static string MenuSocialNews {
            get {
                return ResourceManager.GetString("MenuSocialNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Электронные сервисы.
        /// </summary>
        public static string MenuSoftware {
            get {
                return ResourceManager.GetString("MenuSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вакансии.
        /// </summary>
        public static string MenuVacancies {
            get {
                return ResourceManager.GetString("MenuVacancies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обращения.
        /// </summary>
        public static string MenuWindow {
            get {
                return ResourceManager.GetString("MenuWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш почтовый индекс и адрес места жительства (места пребывания) *.
        /// </summary>
        public static string MessageAdress {
            get {
                return ResourceManager.GetString("MessageAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на * – Поля, обязательные для заполнения.
        /// </summary>
        public static string MessageAttention {
            get {
                return ResourceManager.GetString("MessageAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить.
        /// </summary>
        public static string MessageButton {
            get {
                return ResourceManager.GetString("MessageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите символы с картинки *.
        /// </summary>
        public static string MessageCaptcha {
            get {
                return ResourceManager.GetString("MessageCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес электронной почты для ответа Вам *.
        /// </summary>
        public static string MessageEmail {
            get {
                return ResourceManager.GetString("MessageEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прикрепить файл (до 2Mb в форматe PDF, DOCX, DOC, RTF, TXT, ODT, ZIP, RAR, PNG, TIFF, JPEG, JPG).
        /// </summary>
        public static string MessageFile {
            get {
                return ResourceManager.GetString("MessageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Почтовый индекс и адрес нахождения юридического лица *.
        /// </summary>
        public static string MessageLegalAdress {
            get {
                return ResourceManager.GetString("MessageLegalAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полное наименование юридического лица *.
        /// </summary>
        public static string MessageLegalSender {
            get {
                return ResourceManager.GetString("MessageLegalSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия, собственное имя, отчество (если таковое имеется) либо инициалы руководителя или лица, уполномоченного в установленном порядке подписывать обращения *.
        /// </summary>
        public static string MessageLegalSenderName {
            get {
                return ResourceManager.GetString("MessageLegalSenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия, собственное имя, отчество (если таковое имеется), либо инициалы физ. лица *.
        /// </summary>
        public static string MessagePersonSender {
            get {
                return ResourceManager.GetString("MessagePersonSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование, адрес организации и должность лица, которым направляется обращение *.
        /// </summary>
        public static string MessageReceiver {
            get {
                return ResourceManager.GetString("MessageReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изложение сути обращения (до 2500 символов) *.
        /// </summary>
        public static string MessageText {
            get {
                return ResourceManager.GetString("MessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тема обращения *.
        /// </summary>
        public static string MessageTheme {
            get {
                return ResourceManager.GetString("MessageTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В строительстве задействованы следующие филиалы:.
        /// </summary>
        public static string ObjectDeps {
            get {
                return ResourceManager.GetString("ObjectDeps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Электронное обращение юридических лиц.
        /// </summary>
        public static string OneWindowLegal {
            get {
                return ResourceManager.GetString("OneWindowLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Электронное обращение физических лиц.
        /// </summary>
        public static string OneWindowPerson {
            get {
                return ResourceManager.GetString("OneWindowPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Корпоративная платформа.
        /// </summary>
        public static string Platform {
            get {
                return ResourceManager.GetString("Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование товара.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Примечание.
        /// </summary>
        public static string ProductNote {
            get {
                return ResourceManager.GetString("ProductNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Единица измерения.
        /// </summary>
        public static string ProductUnit {
            get {
                return ResourceManager.GetString("ProductUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Специалист по работе с общественностью.
        /// </summary>
        public static string PublicSpecialist {
            get {
                return ResourceManager.GetString("PublicSpecialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предмет закупки.
        /// </summary>
        public static string PurchaseContent {
            get {
                return ResourceManager.GetString("PurchaseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата закупки.
        /// </summary>
        public static string PurchaseDate {
            get {
                return ResourceManager.GetString("PurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cкачать.
        /// </summary>
        public static string PurchaseDownload {
            get {
                return ResourceManager.GetString("PurchaseDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На данный момент закупок нет!.
        /// </summary>
        public static string PurchaseNot {
            get {
                return ResourceManager.GetString("PurchaseNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Организатор.
        /// </summary>
        public static string PurchaseOrganizer {
            get {
                return ResourceManager.GetString("PurchaseOrganizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cтраница:.
        /// </summary>
        public static string PurchasePage {
            get {
                return ResourceManager.GetString("PurchasePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Техническое задание.
        /// </summary>
        public static string PurchaseTT {
            get {
                return ResourceManager.GetString("PurchaseTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вид процедуры закупки.
        /// </summary>
        public static string PurchaseType {
            get {
                return ResourceManager.GetString("PurchaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приёмная.
        /// </summary>
        public static string Reception {
            get {
                return ResourceManager.GetString("Reception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приёмная факс.
        /// </summary>
        public static string ReceptionFax {
            get {
                return ResourceManager.GetString("ReceptionFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ул. Чичерина, 19, 220029, г. Минск, тел. (017) 365 46 80 факс (017) 365 44 90, rupbes.by, e-mail: rupbes@rupbes.by, р/с BY81 AKBB 3012 6367 5000 2540 0000 в ЦБУ № 527 ОАО «АСБ Беларусбанк», БИК AKBBBY2X, ул. Воронянского, 7а, г. Минск, УНП 100056165, ОКПО 001179725000.
        /// </summary>
        public static string Requisites {
            get {
                return ResourceManager.GetString("Requisites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш адрес электронной почты.
        /// </summary>
        public static string ResponseVacancyEmail {
            get {
                return ResourceManager.GetString("ResponseVacancyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваше имя *.
        /// </summary>
        public static string ResponseVacancyFirstName {
            get {
                return ResourceManager.GetString("ResponseVacancyFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузите сюда Ваше резюме.
        /// </summary>
        public static string ResponseVacancyForm1 {
            get {
                return ResourceManager.GetString("ResponseVacancyForm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на краткую анкету.
        /// </summary>
        public static string ResponseVacancyForm2 {
            get {
                return ResourceManager.GetString("ResponseVacancyForm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша фамилия *.
        /// </summary>
        public static string ResponseVacancyLastName {
            get {
                return ResourceManager.GetString("ResponseVacancyLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш номер телефона для связи *.
        /// </summary>
        public static string ResponseVacancyPhone {
            get {
                return ResourceManager.GetString("ResponseVacancyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузите Ваше резюме.
        /// </summary>
        public static string ResponseVacancyResume {
            get {
                return ResourceManager.GetString("ResponseVacancyResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Откликнуться.
        /// </summary>
        public static string ResponseVacancySubmit {
            get {
                return ResourceManager.GetString("ResponseVacancySubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сопроводительное письмо (до 2500 символов).
        /// </summary>
        public static string ResponseVacancyText {
            get {
                return ResourceManager.GetString("ResponseVacancyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здесь Вы можете указать контактную и другую информацию о себе: навыки, достижения, хобби..
        /// </summary>
        public static string ResponseVacancyTextPlaceholder {
            get {
                return ResourceManager.GetString("ResponseVacancyTextPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Написать отзыв.
        /// </summary>
        public static string ReviewAdd {
            get {
                return ResourceManager.GetString("ReviewAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить.
        /// </summary>
        public static string ReviewButton {
            get {
                return ResourceManager.GetString("ReviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Организация.
        /// </summary>
        public static string ReviewCompanyName {
            get {
                return ResourceManager.GetString("ReviewCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        public static string ReviewDate {
            get {
                return ResourceManager.GetString("ReviewDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ещё не добавлено ни одного отзыва.
        /// </summary>
        public static string ReviewNoReview {
            get {
                return ResourceManager.GetString("ReviewNoReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст отзыва *.
        /// </summary>
        public static string ReviewReviewText {
            get {
                return ResourceManager.GetString("ReviewReviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отзыв.
        /// </summary>
        public static string ReviewText {
            get {
                return ResourceManager.GetString("ReviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отзывы.
        /// </summary>
        public static string ReviewTitle {
            get {
                return ResourceManager.GetString("ReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название Вашей компании * .
        /// </summary>
        public static string ReviewYourCompanyName {
            get {
                return ResourceManager.GetString("ReviewYourCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш Email для обратной связи *.
        /// </summary>
        public static string ReviewYourEmail {
            get {
                return ResourceManager.GetString("ReviewYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бел.
        /// </summary>
        public static string SecLang {
            get {
                return ResourceManager.GetString("SecLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на be.
        /// </summary>
        public static string SecLangVal {
            get {
                return ResourceManager.GetString("SecLangVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите категорию товара.
        /// </summary>
        public static string SelectGroupProduct {
            get {
                return ResourceManager.GetString("SelectGroupProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аренда техники.
        /// </summary>
        public static string ServiceMech {
            get {
                return ResourceManager.GetString("ServiceMech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продукция собственного производства.
        /// </summary>
        public static string ServiceProduct {
            get {
                return ResourceManager.GetString("ServiceProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аренда недвижимости.
        /// </summary>
        public static string ServiceRealty {
            get {
                return ResourceManager.GetString("ServiceRealty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продажа имущества.
        /// </summary>
        public static string ServiceSale {
            get {
                return ResourceManager.GetString("ServiceSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Строительные и монтажные работы.
        /// </summary>
        public static string ServiceService {
            get {
                return ResourceManager.GetString("ServiceService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Программные средства.
        /// </summary>
        public static string ServiceSoftware {
            get {
                return ResourceManager.GetString("ServiceSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контактная информация.
        /// </summary>
        public static string TenderContacts {
            get {
                return ResourceManager.GetString("TenderContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата и время окончания торгов.
        /// </summary>
        public static string TenderFinishDate {
            get {
                return ResourceManager.GetString("TenderFinishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        public static string TenderLink {
            get {
                return ResourceManager.GetString("TenderLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер закупки.
        /// </summary>
        public static string TenderNumber {
            get {
                return ResourceManager.GetString("TenderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закупки с Icetrade.by.
        /// </summary>
        public static string Tenders {
            get {
                return ResourceManager.GetString("Tenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Eng.
        /// </summary>
        public static string ThreeLang {
            get {
                return ResourceManager.GetString("ThreeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на en.
        /// </summary>
        public static string ThreeLangVal {
            get {
                return ResourceManager.GetString("ThreeLangVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пока вакансий нет.
        /// </summary>
        public static string VacanciesNoVacancy {
            get {
                return ResourceManager.GetString("VacanciesNoVacancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОАО «Западэлектросетьстрой».
        /// </summary>
        public static string Zapadelectrosetstroi {
            get {
                return ResourceManager.GetString("Zapadelectrosetstroi", resourceCulture);
            }
        }
    }
}
